package com.wxn.miaosha.dataobject;

import lombok.Data;

@Data
public class UserPasswordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.id
     *
     * @mbg.generated Sat Aug 28 10:55:49 CST 2021
     */
    private Integer id;

    @Override
    public String toString() {
        return "UserPasswordDO{" +
                "id=" + id +
                ", encrptPassword='" + encrptPassword + '\'' +
                ", userId=" + userId +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.encrpt_password
     *
     * @mbg.generated Sat Aug 28 10:55:49 CST 2021
     */
    private String encrptPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_password.user_id
     *
     * @mbg.generated Sat Aug 28 10:55:49 CST 2021
     */
    private Integer userId;


}